In [1]:
import snap
import numpy as np

## 0. Loading Graph

In [2]:
G = snap.LoadEdgeList(snap.PNGraph, "stackoverflow-Java.txt", 0, 1)

## 1. The number of weakly connected components in the network

In [3]:
CnComV = snap.TCnComV()
snap.GetWccs(G, CnComV)
print(CnComV.Len())

10143


## 2. The number of edges and the number of nodes in the largest weakly connected component

In [4]:
Gcom = snap.GetMxWcc(G)
print(Gcom.GetNodes(), Gcom.GetEdges())

131188 322486


## 3. IDs of the top 3 most central nodes in the network by PagePank scores

In [5]:
PRankH = snap.TIntFltH()
snap.GetPageRank(G, PRankH)
IDs = np.array([ID for ID in PRankH])
PRankScores = np.array([PRankH[ID] for ID in PRankH])
rank = np.argsort(PRankScores)
print(IDs[rank[-1:-4:-1]])

[992484 135152  22656]


## 4. IDs of the top 3 hubs and top 3 authorities in the network by HITS scores

In [6]:
NIdHubH = snap.TIntFltH()
NIdAuthH = snap.TIntFltH()
snap.GetHits(G, NIdHubH, NIdAuthH)

In [7]:
# sort by hubs
IDs = np.array([ID for ID in NIdHubH])
Hubs = np.array([NIdHubH[ID] for ID in NIdHubH])
rank = np.argsort(Hubs)
print(IDs[rank[-1:-4:-1]])

[ 892029 1194415  359862]


In [8]:
# sort by hubs
IDs = np.array([ID for ID in NIdAuthH])
Auths = np.array([NIdAuthH[ID] for ID in NIdAuthH])
rank = np.argsort(Auths)
print(IDs[rank[-1:-4:-1]])

[ 22656 157882 571407]
